[package]
name = "devdock"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.15.0"
futures-util = "0.3.29"
log = "0.4.20"
rocket = "0.5.0"
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
