[package]
name = "devdock"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.15.0"
cookie = "0.18.0"
dotenvy = "0.15.7"
futures-util = "0.3.29"
graph-rs-sdk = "1.1.3"
log = "0.4.20"
oauth2 = "4.4.2"
rocket = "0.5.0"
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }